### ISSUE TITLE
I think thet the default should be https

### ISSUE THREAD

**Issue by diegograsso** [airswap/airswap-maker-kit#44]
Hello, 
I the documentation says that:
```Locators take the form of hostname[:port][/path] and resolve to web servers that implement the Maker API. The max length is 32 characters and https:// is implied.```
If my English is good, I understand that if theres no `https` in the locator it's assumed. 
I tested it and the following script fails because it assumes `http`

https://github.com/airswap/airswap-maker-kit/blob/dd286264a0db66ad38d1d8a2cab05fb31b8e290a/scripts/peers/handlers.js#L68

**Comment by dmosites** [comment]
Hi @diegograsso that's right, we'll make that change. Thanks for reporting.

**Comment by perich** [comment]
Resolved by https://github.com/airswap/airswap-maker-kit/pull/45
